typography_spectrum: 0.9476196928881109
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8554827503394336
  lightness: 0.2446768635418266
  saturation: 0.17900791368447244
  rhythmicContrast: 0.9508376221638173
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.20718660368584096
analytics:
  google: null
  facebook: null
  twitter: null
name: New Way
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: A New Way
description: The way to somewhere can always be different
purpose: []
